---
- hosts: all
  roles:
  - { role: dynatrace.Dynatrace-Agents, tags: agents }
  - { role: dynatrace.Dynatrace-Apache-HTTPServer-Agent, tags: apache-agent }
  - { role: dynatrace.Dynatrace-Client, tags: client }
  - { role: dynatrace.Dynatrace-Collector, tags: collector }
  - { role: dynatrace.Dynatrace-Fixpack, tags: fixpack }
  - { role: dynatrace.Dynatrace-Glassfish-Agent, tags: glassfish-agent }
  - { role: dynatrace.Dynatrace-Java-Agent, tags: java-agent }
  - { role: dynatrace.Dynatrace-License, tags: license }
  - { role: dynatrace.Dynatrace-Plugin, tags: plugin }
  - { role: dynatrace.Dynatrace-Server, tags: server }
  - { role: dynatrace.Dynatrace-Tomcat-Agent, tags: tomcat-agent }
  - { role: dynatrace.Dynatrace-WebServer-Agent, tags: wsagent }
  remote_user: deploy
