---
- name: Check if the Dynatrace installer is provided locally
  local_action:
    module: stat
    path: "{{ playbook_dir }}/roles/{{ dynatrace_agent_role_name }}/files/linux/{{ dynatrace_agent_linux_installer_file_name }}"
  register: dynatrace_agent_installer_file_provided

- name: "Copy the Dynatrace installer to {{ dynatrace_agent_linux_root_dir }} if the installer is provided locally"
  copy:
    src: "{{ playbook_dir }}/roles/{{ dynatrace_agent_role_name }}/files/linux/{{ dynatrace_agent_linux_installer_file_name }}"
    dest: "{{ dynatrace_agent_linux_root_dir }}/"
  when: (dynatrace_agent_installer_file_provided.stat.exists == True and dynatrace_agent_installer_downloaded.stat.exists == False)
  become: yes

- name: "Download the Dynatrace installer to {{ dynatrace_agent_linux_root_dir }} if the installer is not provided locally"
  get_url:
    url: "{{ dynatrace_agent_linux_installer_file_url }}"
    dest: "{{ dynatrace_agent_linux_root_dir }}"
    owner: "{{ dynatrace_agent_owner }}"
    group: "{{ dynatrace_agent_group }}"
    mode: u+rwx
    validate_certs: False
  when: (dynatrace_agent_installer_file_provided.stat.exists == True and dynatrace_agent_installer_downloaded.stat.exists == False)
  become: yes

- debug: msg="yes | {{ java_home_path }}/{{ jre_exe }} -jar {{ dynatrace_agent_linux_installer_file_name }}"

# - name: Install the Dynatrace Agent
#   shell: "{{ jre_exe }} -jar {{ dynatrace_agent_linux_installer_file_name }}"
#   args:
#     chdir: "{{ dynatrace_agent_linux_root_dir }}"
#     executable: /usr/bin/bash
#   become: yes
#   become_user: root
#
# - include_tasks: facts/set-dyna-facts.yml
#   become: true
#
# - debug:
#     var: dynatrace_agent_installed_version_path
#     verbosity: 3

# - name: Change ownership of the installation directory
#   file:
#     path: "{{ dynatrace_agent_installed_version_path }}"
#     owner: "{{ dynatrace_agent_owner }}"
#     group: "{{ dynatrace_agent_group }}"
#     state: directory
#     recurse: yes
#   become: yes
#
# - name: Change mode of the installation directory
#   file:
#     path: "{{ dynatrace_agent_installed_version_path }}"
#     mode: 0775
#   become: yes
#
# - name: "Create a symlink of the actual installation directory to {{ dynatrace_agent_linux_install_dir }}/dynatrace"
#   file:
#     src: "{{ dynatrace_agent_installed_version_path }}"
#     dest: "{{ dynatrace_agent_linux_install_dir }}/dynatrace"
#     owner: "{{ dynatrace_agent_owner }}"
#     group: "{{ dynatrace_agent_group }}"
#     mode: 0775
#     state: link
#   become: yes
#
# - name: Remove the Dynatrace Agent installer
#   file:
#     path: "{{ dynatrace_agent_linux_install_dir }}/{{ dynatrace_agent_linux_installer_file_name }}"
#     state: absent
#   become: yes
#
# - name: Update Dynatrace NGINX symbol offsets file
#   unarchive:
#     src: linux/dtnginx_offsets.json.tar.gz
#     dest: "{{ dynatrace_agent_installed_version_path }}/agent/conf"
#   become: yes
