---
# BACKLOG:70 create uninstall plays
# DONE:10 check if installed
# BACKLOG:60 analyze if I need to use uninstaller or can just delete
# BACKLOG:50 add uninstall tags for more flexible playbook use
# BACKLOG:30 Tags everywhere
- name: "stat dynatrace install dir"
  stat:
    path: "{{ dynatrace_agent_linux_install_dir }}/"
  register: dynatrace_agent_linux_installed.stat.exists
  become: yes


- name: Change ownership of the installation directory if it had to be created
  file:
    path: "{{ dynatrace_agent_linux_install_dir }}"
    state: absent
  when: dynatrace_agent_linux_installed != 0
  become: yes
